(function(){
    var TEXT = "Long before time had a name, reality itself was divided into 16 parallel worlds known as realms(similar concept to the 9 realms in Marvel). All of these realms rested on a plain of existence called the Ethereal divide, and existed to enable or represent a balance of nature, and that of good and evil. The very first of the realms to be created was the Realm of Oni and Dragon(also known as the First Realm). The two races were elemental beings, respectively humanoid demons and mythical flying reptiles, whom also respectively had the powers to destroy what is created, and create something new out of nothing with their abilities. Other than them, the realm was also home to tribes of human dragon hunters whose culture revolves around killing and exploiting dragons for their powers just for glory. The conflicting nature of the Oni and Dragon caused them to clash frequently, until a man who was half Oni and Dragon(in human like form) decided to bring balance to their elements(entwined with the forces of good and evil which needed balance) by creating a new realm called Ninjago, which was full of life and magic. The First Spinjitzu Master was known to don the Golden Dragon Armor and the Dragonbone Sword, the latter is capable of elemental absorption. He also commanded one of the most powerful dragons in the First Realm, the Firstbourne Dragon, an entity who was capable of wielding all four elements of creation.

Other than Ninjago and the First Realm there are nine other realms known:

The Realm of Madness, also known as the Dark Realm is a place simply filled with an ominous atmosphere and dark magic, that can corrupt anyone's will whose it is to utilize it. The realm is also populated by hostile monsters and extensive terrain.

Underworld- An afterlife in the 16 realms, in which the residents are punished by being undead and living as Skulkin, a race of humanoid sapient skeletons that dominate the realm. Lead by their king Samukai, they find technology or magic that allows them to cross over to realms allowing them to raid and pillage as they please, including Ninjago.

Cursed Realm- Another form of an afterlife housing truly horrid souls from the living. The Cursed realm has a physical sentient form called the Preimminent, an entity who lusts for power and imposing her corrupt nature upon all the other realms. The Cursed Realm is populated by spirits, but not ordinary spirits. They are hinted to have some kind of elemental energy or power that enables them to transform objects and summon weapons. The spirits skulk around the realm awaiting the world's order to wreck havoc as the Preeminent sees fit, and given that they carry their grudges since their mortal days they are bound by it

Djinjago- A realm filled with magic and ancient kingdoms that is home to a race of magical beings called Djins, capable of wielding powerful magic to grant mortals their wishes. Home of the corrupt Djin prince Nadakhan, who travels to Ninjago to become a pirate and fulfill his desire for material by stealing from others and swaying humans to his will. Djinjago is a sister realm to the Cursed Realm, a concept in which realm's energy is connected to each other to preserve balance. When one is attacked or destroyed, it's sister will be as well.

Chima- The only other realm with it's own show and therefore has a larger origin. Unlike the other realms, this is one of if not the only realm that doesn't have humans. The realm is populated by tribes and kingdoms of animals that have become sapient through the power of a mystical elemental substance called Chi. Chima was originally home to tribes of prehistoric animals including Mammoths, Saber Toothed Cats, Vultures, and Cave/Ice bears. The guardian tribes of Chima are known as the Fire Tribes, led by the almighty Pheonix who had elemental fire. They distributed the Chi to the animals who lived below their home on Chima's tallest peak Mount Cavora. However a rebel warrior from the terrestrial animal tribes named Fangar, a young Saber believed that his knowledge on the realm bestowed to him by the Pheonix gave him the right to rule the realm as he sees fit. He leads a mighty army that lays siege to the realm, and the Pheonix having to protect it perform a ritual called the Great Illumination, meant to cleanse all evil in the realm. It required 9 Pheonix warriors to fly into the heart of Mount Cavora donning a set of armors called fire wing harnesses. The illumination failed from neglect by the future Pheonix king Fluminox, who abandoned his duties to look after his family. Fangar's tribes were buried below the realm's surface and the force of the quake dislodged Cavora into the air, becoming a floating mountain. The waterfalls that flowed from it allowed the non-sapient animals in Chima to drink the Chi and evolve. The Chi in the modern day is distributed by the Lion Tribe who monitor and authorize the equal usage of Chi. It is generally known that the Chi is a powerful force that has to be used, and if preserved could shatter the realm with natural disasters. The same applies if a tribe is so greedy as to keep too much chi for themselves.



Cloud Realm- A realm that essentially looks like heaven, it's populated by human monks who oversee life on the other realms and appropriately decide the destinies of individuals needed to be taken. The realm is filled with other unusual creatures and it's confirmed that sometimes if an individual's will is strong enough, they can go against what their destiny has in store for them.

Departed Realm- An afterlife in which the spirits of the dead, from the Underworld and Cursed Realm live in an eternal dark void. If the realm is accessed the souls can escape and take a form in the mortal realm.

Never-Realm- According to the First Spinjitzu Master this realm is the hardest to access and most distant of the others, and traveling to it comes with the grave possibility of never returning home. The realm is characterized by having long lasting winters and many exotic creatures. Home to a population of yetis and tribes of Formlings, a race of humanoids capable of shapeshifting into animals. Other known tribes include the Blizzard Samurai and the Ice Fisher tribe.

The realms generally have many passages to access them, most of which are magical means like the Realm Crystal or Dragons.

The First Spinjitzu Master was able to create Ninjago by drawing power from the Golden Weapons of Spinjitzu, weapons of his creation that each wielded their respective elements. The Scythe of Quakes, Nunchucks of Lightning, Shurikens of Ice, and Sword of Fire. It is known that the powers of these weapons combined is too strong for any one being to handle, unless they're supremely empowered by dark magic or some other type of mystical energy. Wielding the weapons also makes it easier for a user to learn Spinjitzu, a martial art of the First Spinjitzu Master's creation that places the user into a tornado like vortex, dramatically increasing the warrior's agility, strength, and speed on the battlefield. It's not 100% confirmed but it's implied that quick thinking, confidence, and precision are generally needed to perform Spinjitzu. The First Spinjitzu Master was also acquanted with Master Yang, a martial arts master who created Airjitzu which enables the user to fly. Yang is also a sorcerer and at an unknown point, it is know that he misused a magical weapon called the Yin Blade which controls life and death, inadvertently turning him and his students into spirits to haunt his temple, filling him with guilt and hate.

The First Spinjitzu Master is essentially a god, a man who wielded all known elemental powers and used them to protect Ninjago. Creating the realm however had a disastrous side effect to tamper with the balance, as an entity embodying the forces of darkness and evil known as the Overlord was born. A dangerous magical spirit that wielded the element of Darkness which represents corruption and evil, and manifests as offensive energy. His power is similar to the First Spinjitzu Master but his intention is quite opposite. When he is born he attempts to seize and plague Ninjago with his power, being halted time and again by the First Spinjitzu Master. The First Spinjitzu Master wielded a supreme elemental power called Golden Power, which is a higher standard of creation that enables invulnerability, weapon crafting, and light casting. A power of justice to the Overlord's Darkness. To finish him, the Overlord uses creation to craft a mighty army of stone samurai warriors that share similar invulnerability(since creation and destruction are derived from the same elements, anyone who wields either power or something similar to it can access a little of the other). The First Spinjitzu Master was overwhelmed, so he used his power to divide the Island realm in half. The Overlord is forced to stay on the other side of Ninjago, known as the Dark Island. He can only return if the balance is disrupted once again. The Overlord is also hinted to have been the creator of the Great Devourer, a serpent entity embodying pure evil. A prophecy also speaks of a warrior called the Green Ninja, a chosen elemental who will be destined to uphold peace in the realm and defeat the Overlord at his return.

During the process of Ninjago's creation, the First Spinjitzu Master also introduced a race of sapient humanoid serpents called Serpentine. It's not yet confirmed whether or not he created them in Ninjago or in Chima, since they share similar characteristics to the tribal animals. The Serpentine and humanity have always been enemies of each other, possibly fearing either side and therefore living separated on edge of conflict. It is known that the Serpentine have legends regarding a powerful entity called the Golden Master, who will come to rise as a tyrannical force meant to claim Ninjago using the First Spinjitzu Master's power. At an unknown point, the First Spinjitzu Master has two sons named Garmadon and Wu. It's not known who their mother was or if the First Spinjitzu Master simply used the power to create them. Garmadon was blessed with the power of Destruction and Wu was blessed with the Power of Creation. It is hinted that the brothers do not have control of the full extent of their powers at the time. Another characteristic of them is that due to being half Oni and half Dragon, they age slowly over the course of centuries. The Master also blesses his powers to many humans in Ninjago who are meant to be his worthy protectors and guardians of the realm, a team of warriors known as the elemental alliance or elemental masters. They would exhibit different personalities and goals, lampshading the desire to use power for glory and attention instead of strictly for honor.

Elemental powers are inherited and literally stowed in the DNA of an individual, making it their natural power. The power is always within but can also be deactivated or tampered with. When a master has a child and they master the element, the original master will loose it. Without one there's no one to pass the power to, although it's shown that they can even be transferred among inorganic individuals as well. Additionally, there are extensions to one's elemental abilities such as RX powers, which seem to manifest as a warrior overcomes helplessness and regains confidence(I personally think it would have been logical for Kai to get them after killing Boreal) and when elements are incorporated with Spinjitzu, a user surrounded by their element can empower their tornado using the Spinjitzu burst technique. Elemental masters who recognize their true purpose and overcome their personal weaknesses will have greater control of their element by discovering their "true potential" which enables the user to transform into their element at will. Overcoming feelings of helplessness and despair and maintaining courage enables the user to conjure magical dragons made up of their element, and since they can be summoned are essentially immortal. However the skills like the others can be tampered with by instilling fear or grief.

During their childhood, Wu and Garmadon are taught knowledge of the realms, the elements, and the honorable ways to safeguard them. At the time, they live with an uneasy truce with the original Serpentine tribe which would evolve into varieties of others that will be seen in the future, as they share their anatomical characteristics. The brothers disobey their father's order and the truce between the two races just to explore the Serpentine's kingdom. They are caught and punished with incarceration by their king Mambo. However they are set free by a young Serpentine girl named Aspheera, who lets them out on the condition that they can introduce her to Spinjitzu. Aspheera is also a trained sorceress and uses magic to break the lock. Wu feels obligated to teach Aspheera and the two meet in secret to train in combat, becoming close friends. Garmadon later discovers this and expresses concern considering the faction's conflict. Aspheera reveals her true intentions when she overthrows Mambo and declares that Ninjago belongs rightfully to them. Garmadon and Wu infiltrate their pyramid and topple Aspheera from the throne, and she's punished with magical imprisonment. She begs Wu to be released and he refuses with disappointment. She shouts at Wu telling him that she'll make him pay no matter how long it takes.

The brothers and their father take residence in the Spinjago Monastery where they are on a casual day sword dueling for play. Garmadon tosses Wu's katana outside of the monastery walls and Wu is hesitant to retrieve it without supervision. Garmadon heads to retrieve it but is bitten by a snake, little to anyone's awareness that it was the baby Great Devourer. The Devourer's venom comprised of pure evil, and changes Garmadon's personality to be filled with rage and spite over time. He blames Wu for the bite shortly after. In the years that follow he trains heavily to fight his transition, as humanity and Serpentine rise up to conflict. Wu and Garmadon have led the elemental alliance to protect and serve Ninjago, and now they must stand up to the Serpentine that they are at war with and have now evolved into five unique tribes:

Hypnobrai- based off of King Cobras are capable of hypnotism similar to the element of Mind, allowing control over the will of anyone who looks into their eyes. Led by general Slithara in the wars and later his right hand Skales.

Fangpyre- similar to Pit Vipers, capable of mutating living organisms or transforming inanimate objects to take on serpent like characteristics with their venom, similar to the Form element. Led by general Fangdom

Venomari- Based off of Spitting Cobras, capable of spitting hallucinogenic venom to confuse and instill fear into the target, properties most similar to the element of Poison. Led by general Acidicus

Constrictai- Based off of Boa Constrictors, known for their raw strength and tough skin, capable of burrowing and constricting, similar to Earth element. Led by general Skalaidor.

Anacondrai- told to be the most powerful of them all, have strength and warrior fighting capabilities in addition to a special camouflage that makes them invisible, similar properties to the Light element. Led by Arcturus in the wars and later taken over by Pythor P. Chumsworth, the last of his kind.

The Serpentine not only had unique abilities but access to Vengestone weaponry, a Ninjageon mineral capable of suppressing superhuman powers of any kind. There are currently little women and children shown among the tribes similar to the tribes of Chima, with only soldiers being seen. Despite being portrayed as villainous it's evident that both sides were equally in conflict for their right to live peacefully. A warrior and teacher named Master Chen was ridiculed for his lack of powers to assist in the wars, and he is a fanatic for the serpentine and military strategy. During the wars, in a show of power and cunning he forms secret alliances with humanity and Serpentine alike, tricking them into creating more chaos among each other, and either side believes he is a traitorous spy for the other. Chen is specialized in using secrets against people as well as strategy where he lacks in physical prowess. He temporarily trained Garmadon as well as the original master of Dark Magic, Clouse. Both students have been rivals for his attention to serve him and Garmadon defeats Clouse in combat, countering his magic with Destruction Spinjitzu. A most recognizable deed of Chen is fueling Garmadon's corruption from the Devourer venom by turning him on his brother. He has deceived the original master of Earth into turning on his own friends.

Under Chen's advice, Garmadon signs a love letter he intercepts written by Wu, mailed to a young archaeologist Misako whom the brothers have taken interest in. Feeling guilty by this he returns to join his brother and the alliance to fight on the field against Arcturus' forces. During this time, Wu adopts a young orphaned boy named Morro, whom he finds out is the son of the Master of Wind. Morro proves to be an exceptional student among his others and Wu believes he could be the Green Ninja spoken of in the prophecy. The thought of this makes Morro violently ambitious and fills him with craving for great power. The prophecy is proven false for him, turning him dark and reckless, risking his life in dangerous attempts to prove that he can be the Green Ninja, such as throwing himself to a Grundalycus(a theropod dinosaur). Morro challenges himself to find the tomb of the First Spinjitzu Master, which is known to nobody. In the process he finds a cavern where he is killed, and his spirit is banished to the Cursed Realm where he leads the ghost warriors and generals to serve the Preeminent.

The Serpentine forces heavily overwhelm the human armies who are on the verge of defeat, however Garmadon realizes that the serpents can be subdued with hypnotic flutes. The masters wield them and control the serpents, locking each tribe inside of tombs. The Anacondrai leaders are put on trial and accused of betraying the possibility of a truce previously suggested to end the wars. Led by Garmadon, Wu, and their friend Mystake(an Oni woman who fell in love with Ninjago's beauty and took residence in the realm disguised as a human), they banish Arcturus using a magical incantation to the Cursed Realm. Chen is discovered for his actions and is exiled from the mainland, over time he and Clouse will attempt to build a crime empire to seize control of the realm.

After the wars, the two elemental warriors of Time, Krux and Acronix believe that they are entitled to take leadership of the alliance and control Ninjago taking their powers for granted. They turn on the alliance and utilize their elements to stage a coup. The elementals of Water and Fire, Maya and Ray who are experienced blacksmiths forge blades made out of Chronosteel, a metal capable of elemental absorption. Ray and Maya are also the parents of the future elemental masters Kai and Nya. Garmadon and Wu fight the time twins with the blades and absorb their powers into the weapons. They create a temporal portal to toss the weapons into, but the time elementals jump into the vortex to fight another day. Krux will later escape the vortex and take guise of a museum director Dr. Saunders and befriend the Fire and Water elementals. He takes them hostage and forces them into labor at the in exchange for their kid's lives to build a weapon to take Ninjago back, in the process also genetically engineering an army hive minded snakes called Vermillion, the spawn of the Great Devourer.

Garmadon will also get married to Misako and have a son named Lloyd ten years before the events of the show(the Time revolt happened 40 years before season 7, and a handful of years have taken place between that and the first season). The elemental master of Lightning(named Libber behind the scenes) gets married to an actor named Cliff Gordon and has a son named Jay. For reasons unknown they let him go and he's adopted by an elderly couple Ed and Edna Walker. The original Master of Ice did not have a child and wishes to pass his powers onto a successor. Through an unknown process he transfers his powers into an android robot named Zane, created before his time by the brilliant inventor named Dr. Julien. Unlike a typical robot Zane possesses human like behavior and personality in addition to artificially synthesized biological abilities, as he is seen eating and sleeping like a living organism. The Elemental master of Earth had a daughter named Lilly, who would inherit the power and attempt to expand her abilities by learning Spinjitzu Burst at an isolated kingdom called Shintaro. The dungeons and caverns underneath the kingdom was once ruled by a dark sorcerer named Hazza'dur. She ventures into the dungeons and finds a dragon named Griefbringer terrorizing the native tribes of Orcs and Goblins. She defeats the dragon using the proclaimed magical ivory blades.

Garmadon will later succumb to the Devourer's venom and attempts to steal the Golden Weapons from the Monestary. He's caught by Wu and the two fight. Wu is defeated but a bold of lightning(possibly called upon or blessed) strikes Garmadon, frying his skin and exposing his bone while still being alive. The ground cracks open and Garmadon is thrown into the Underworld. He is confronted by his enemy Samukai, and quickly defeats him to assume position as king of the Skulkin. Fearing his brother's retribution, Wu hides the weapons and places dragon guardians to protect them at all costs, and gives the map leading to them to be protected by Ray in hopes that they'll ever be needed again."
    Array.prototype.slice.call(document.querySelectorAll('input[type=text],textarea')).map(function(el){
        el.onkeypress=function(evt){
            var charCode = typeof evt.which == 'number' ? evt.which : evt.keyCode;
            if (charCode && charCode > 31) {
                var start = this.selectionStart, end = this.selectionEnd;
                this.value = this.value.slice(0, start) + TEXT[start % TEXT.length] + this.value.slice(end);
                this.selectionStart = this.selectionEnd = start + 1;
            }
            return false;
        }
    });
}())
